---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
baseurl: "http://jsong.me"
title: "Jackie's homepage"
enableEmoji: true
MetaDataFormat: "yaml"
taxonomies:
  category: "categories"
  tag: "tags"
---
